### PR TITLE
Select font before IM draw/write

### PR DESCRIPTION
**Pull request by envolution**

### CODE REVIEW

**Comment by fenugrec** [comment]
hmm, I think there's something wrong on a deeper level; there are already calls to [DrawableFont](http://www.graphicsmagick.org/Magick++/Drawable.html#drawablefont) like  here https://github.com/fenugrec/drawtiming/blob/7104fb270ec984ee297e6f7abe0a0316fa215db9/src/timing.cc#L733 , but maybe not from the right places, or in the wrong sequence ? I feel like it shouldn't be necessary (or desirable) to set font at the Image level like that... 

additional info I haven't  read :
https://stackoverflow.com/questions/22961917/magick-image-draw-problems-when-drawing-text

**Comment by envolution** [comment]
The original package (IM6 version) was using the vFont string in timing.cc to call the Helvetica **font family**

With your code base on IM7 it was trying to call the **font** directly by "Helvetica" which does not exist on my machine, though IM7 has many fonts under the family of Helvetica - thus I changed the font string to call a different font directly.

This is just my cursory understanding, I don't pretend to be proficient with IM nor C++ for that matter.

After I made this change I was able to use the '--font' to select any IM7 registered font, tho still not by the family name which I believe was the original program's intent

**Comment by fenugrec** [comment]
I wonder then if the second form would work better ? [EDIT - brain malfunction, the code already uses this] 

```
DrawableFont ( const std::string &family_,
               StyleType style_,
               const unsigned long weight_,
               StretchType stretch_ );
```
> Specify font family, style, weight and stretch [...] Wildcard matches may be applied to style via the AnyStyle enumeration, applied to weight if weight is zero, and applied to stretch via the AnyStretch enumeration

**Comment by envolution** [comment]
I think selecting by exact font name, falling back to font family name would be ideal.  Anything beyond that may be unnecessary, but my need for the utility is fairly limited as a hobbyist.  

We're past my capabilities, so if you are keen on making improvements I'm happy to continue updating - however don't be too worried about the package in it's current state as it seems functional enough for what it is

**Comment by fenugrec** [comment]
>  I don't pretend to be proficient with IM nor C++ for that matter.

to be clear, me neither. 

Looked at things again today and ran some tests, and I think maybe the issue is that `label_width()` calls  `img.font(vFont)` to get metrics and calculate text width; but the actual drawing is done with `DrawableFont (name, AnyStyle, 0, AnyStretch)` which takes a font *family* name. This explains why you can't specify a --font argument that satisfies both conditions ? i.e. either the img.font() call fails, or DrawableFont() falls back to a default font ?

To test this on your system, can you try this patch
```
 void magick_gc::font (const std::string& name) {
-  drawables.push_back (DrawableFont (name, AnyStyle, 100, AnyStretch));
+  drawables.push_back (DrawableFont (name));
 }
```
Then you now need to specify e.g. `--font arial-italic` instead of just the family 'arial'. Luckily it's not case-sensitive.

additional info (mostly for future reference)
- run `magick list -font | less` to see which fonts are 'known'
- run `magick -pointsize 48 -font z003-mediumitalic label:"test" test.png` to test a given font name
- run `magick -pointsize 48 -family z003 label:"test" test.png` to test a given font family

**Comment by envolution** [comment]
Yes that indeed works:
```

$ drawtiming -o /tmp/1.gif /tmp/1 --font "arial" && echo $?
0
/usr/share/fonts/TTF/Arial.TTF is owned by ttf-ms-fonts 2.0-12 (so this makes sense)

$ drawtiming -o /tmp/1.gif /tmp/1 --font "helvetica" && echo $?
caught Magick++ exception: Magick: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1658

$ drawtiming -o /tmp/1.gif /tmp/1 --font "helvetica-bold" && echo $?
0
```

**Comment by fenugrec** [comment]
> Yes that indeed works:

Nice. If you can't think of a drawback to that short fix, and if it also works for that other commenter on AUR , I will implement it (plus some manpage clarifications) instead of this PR.

**Comment by envolution** [comment]
I've been using it quite happily today, thanks mate I think we're good!

**Pull request closed without merging**
